version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: mun-uz-api
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "${BACKEND_EXPOSE}:${BACKEND_PORT}"
    environment:
      - MONGODB_URI=mongodb://mongo:${MONGODB_PORT}/${MONGO_DATABASE}
    env_file: ./.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mun-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${BACKEND_PORT}/api/health"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 30s

  mongo:
    image: mongo:latest
    container_name: mun-uz-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "${MONGODB_EXPOSE}:${MONGODB_PORT}"
    networks:
      - mun-network
    command: mongod --port ${MONGODB_PORT}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "${MONGODB_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  mun-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local