version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mun-uz-api-dev
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/mun-uz
      - PORT=3000
      - JWT_SECRET=development_secret_replace_this_in_production
    networks:
      - mun-network

  mongo:
    image: mongo:4.4
    container_name: mun-uz-mongo-dev
    restart: unless-stopped
    volumes:
      - mongo-data-dev:/data/db
    ports:
      - "27017:27017"
    networks:
      - mun-network

networks:
  mun-network:
    driver: bridge

volumes:
  mongo-data-dev:
    driver: local